ALTER TABLE empresa
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE empresa
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE usuario
    ADD COLUMN IF NOT EXISTS role VARCHAR(20) NOT NULL DEFAULT 'MEMBER';

ALTER TABLE usuario
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE usuario
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE produto
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE produto
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE pedido
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE pedido
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE item_pedido
    ADD COLUMN IF NOT EXISTS created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

ALTER TABLE item_pedido
    ADD COLUMN IF NOT EXISTS updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;

UPDATE usuario
SET role = 'OWNER'
WHERE role IS NULL OR role = 'MEMBER';

CREATE UNIQUE INDEX IF NOT EXISTS uk_empresa_cnpj ON empresa (cnpj);
CREATE UNIQUE INDEX IF NOT EXISTS uk_usuario_email ON usuario (email);
CREATE INDEX IF NOT EXISTS idx_usuario_empresa_id ON usuario (empresa_id);
CREATE INDEX IF NOT EXISTS idx_produto_empresa_id ON produto (empresa_id);
CREATE INDEX IF NOT EXISTS idx_pedido_empresa_id ON pedido (empresa_id);
CREATE INDEX IF NOT EXISTS idx_item_pedido_pedido_id ON item_pedido (pedido_id);
CREATE INDEX IF NOT EXISTS idx_item_pedido_produto_id ON item_pedido (produto_id);
